const { authenticate, optionalAuth, authorize } = require('./auth');
const { errorHandler, notFoundHandler, AppError } = require('./errorHandler');
const { globalLimiter, authLimiter, searchLimiter, apiLimiter } = require('./rateLimiter');
const { uploadAvatar, uploadPlaylistCover, handleUploadError } = require('./upload');
const {
  validate,
  registerValidation,
  loginValidation,
  refreshTokenValidation,
  googleAuthValidation,
  forgotPasswordValidation,
  playlistValidation,
  addSongValidation,
  updatePlaylistValidation,
  reorderValidation,
  updateProfileValidation,
  searchValidation,
  videoIdValidation,
  playlistIdValidation,
  userIdValidation,
  historyIdValidation,
  historyValidation,
  qualityValidation,
} = require('./validation');

module.exports = {
  authenticate,
  optionalAuth,
  authorize,
  errorHandler,
  notFoundHandler,
  AppError,
  globalLimiter,
  authLimiter,
  searchLimiter,
  apiLimiter,
  uploadAvatar,
  uploadPlaylistCover,
  handleUploadError,
  validate,
  registerValidation,
  loginValidation,
  refreshTokenValidation,
  googleAuthValidation,
  forgotPasswordValidation,
  playlistValidation,
  addSongValidation,
  updatePlaylistValidation,
  reorderValidation,
  updateProfileValidation,
  searchValidation,
  videoIdValidation,
  playlistIdValidation,
  userIdValidation,
  historyIdValidation,
  historyValidation,
  qualityValidation,
};